### ISSUE TITLE
Only README

### ISSUE THREAD

**Issue by ajimbong** [Njong392/Portfolio-2.0#1]
I starred the repo just to come and realize there's only a README file 😅😅

Anyways, I presume the code will be pushed later.

**Comment by Njong392** [comment]
Oh... 😂😂😂 i could never imagine any one would be paying attention. Let's hope i pull through with this one and finish it haha

**Comment by ajimbong** [comment]
I saw the notification while scrolling through my GitHub feed.

That's some evidence that I'm not the only one paying attention 😅.

All the best with your project.🥂
